### PR TITLE
Added BatchedObservationWrapper

### PR DESCRIPTION
**Pull request by frenchie4111**
I've added BatchedObservationWrapper which is a small wrapper around BatchedWrapper that makes it easy to perform batched observation modifications.

Example of it in use:

```
class BatchedResizeImageWrapper( BatchedObservationWrapper ):
    def __init__( self, env, size=( 84, 84 ), method=tf.image.ResizeMethod.AREA, **args ):
        config = tf.ConfigProto( device_count={ 'GPU': 0 } )
        self._sess = tf.Session( config=config )
        self._images = tf.placeholder( tf.int32, shape=( None, ) + env.observation_space.shape )
        self._resized = tf.image.resize_images( self._images, size, method=method )

        super( BatchedResizeImageWrapper, self ).__init__( env, **args )

    def observation( self, obses ):
        return self._sess.run( self._resized, { self._images: obses } )
```

### CODE REVIEW

**Comment by unixpickle** [comment]
Whoops, I noticed this PR just now, and it looks like it has some merge conflicts with something similar I did today. I still think it would be nice to get this PR merged, since my current `ObsWrapperBatcher` can't optimize for batches the same way your `BatchedObservationWrapper`.

One thing I don't really understand: why do you assume that the observation space is a Box? That seems like an odd assumption to make. I think the `__init__()` shouldn't be overridden, just like for [gym.ObservationWrapper](https://github.com/openai/gym/blob/master/gym/core.py#L311).

**Comment by frenchie4111** [comment]
I will work on the merge conflicts this evening.

For the observation space changes: It was something I brought over from your `DownsampleEnv` and `GrayscaleEnv`. But you are right, it doesn't make sense for the wrapper to assume the observation space will be a box. I will remove the `__init__()`.

**Comment by frenchie4111** [comment]
Merge conflicts should be fixed now. I added a note to the docstring about how the two Observation Wrappers are different.

**Comment by frenchie4111** [comment]
Actually it just feels really silly to have a `BatchedObsWrapper` and `BatchedObservationWrapper`

**Comment by unixpickle** [comment]
One nitpick: I wrap all docstrings at 60 characters, since it's generally easier for the eye to read narrower columns of text. That being said, I may want to change that restriction in the future, but for now it'd be nice to keep all docstrings consistent.

It's unfortunate that I originally called the wrapper `BatchedObsWrapper` and that I tagged a version on PyPI with this name. Since I want to follow semantic versioning, I can't make a breaking change like deleting `BatchedObsWrapper` unless I jump to version `0.12.0`, which I don't want to do yet. When I do make that jump, I'll delete the `BatchedObsWrapper` and `BatchedActWrapper` aliases.

**Comment by frenchie4111** [comment]
Update docstrings to 60 wide columns

**Pull request merged**
